name: Build and push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

    # Log in to ghcr
      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f Dockerfile.production -t ghcr.io/MathAppPW/Api:latest .

      - name: Push Docker image
        run: docker push ghcr.io/MathAppPW/Api:latest
